services:
  floci:
    image: ${FLOCI_IMAGE:?Copy .env.example to .env}
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:${FLOCI_SERVICES_RDS_PROXY_BASE_PORT:?}-${FLOCI_SERVICES_RDS_PROXY_MAX_PORT:?}:${FLOCI_SERVICES_RDS_PROXY_BASE_PORT:?}-${FLOCI_SERVICES_RDS_PROXY_MAX_PORT:?}"
    environment:
      FLOCI_SERVICES_LAMBDA_DOCKER_FLAGS: ${FLOCI_SERVICES_LAMBDA_DOCKER_FLAGS:?}
      FLOCI_SERVICES_IAM_ENFORCEMENT_ENABLED: ${FLOCI_SERVICES_IAM_ENFORCEMENT_ENABLED:?}
      FLOCI_HOSTNAME: ${FLOCI_HOSTNAME:?}
      FLOCI_SERVICES_DOCKER_NETWORK: ${FLOCI_SERVICES_DOCKER_NETWORK:?}
      FLOCI_SERVICES_RDS_DEFAULT_POSTGRES_IMAGE: ${FLOCI_SERVICES_RDS_DEFAULT_POSTGRES_IMAGE:?}
      FLOCI_SERVICES_RDS_PROXY_BASE_PORT: ${FLOCI_SERVICES_RDS_PROXY_BASE_PORT:?}
      FLOCI_SERVICES_RDS_PROXY_MAX_PORT: ${FLOCI_SERVICES_RDS_PROXY_MAX_PORT:?}
      FLOCI_STORAGE_MODE: ${FLOCI_STORAGE_MODE:?}
      FLOCI_STORAGE_PERSISTENT_PATH: ${FLOCI_STORAGE_PERSISTENT_PATH:?}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:?}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - floci-data:/app/data
    networks:
      - local
networks:
  local:
    name: ${FLOCI_SERVICES_DOCKER_NETWORK:?}
volumes:
  floci-data:
